set autoindent
set ruler

" make launch files read like xml files
syntax on
filetype on
au BufNewFile,BufRead *.launch set filetype=xml

" make backspace work like a normal backspace
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
set ignorecase

" highlight search results
set hlsearch
set incsearch
set magic

"show matching brackets
set showmatch

"Change theme
colorscheme desert
set background=dark

" Turn Backup Off, since most stuff is in SVN
set noswapfile
set nobackup
set nowb

" Tabs and indentation
set smarttab
set shiftwidth=4
set tabstop=4
set ai " auto indent
set si " smart indent

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
" Remember info about open buffers on close
set viminfo^=%

" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()


